export enum TechnologiesNames {
  ANGULAR = 'angular',
  ANGULAR_MATERIAL = 'angular_material',
  TAILWIND = 'tailwindcss',
  TYPESCRIPT = 'typescript',
  JAVASCRIPT = 'javascript',
  RXJS = 'rxjs',
  SASS = 'sass',
  NODEJS = 'nodejs',
  EXPRESS = 'express',
  JWT = 'jwt',
  JAVA = 'java',
  SPRING = 'spring',
  REACT = 'react',
}
