name: "Portfolio Pipeline"
on:
  push:
    branches: [main]
jobs:
  build-and-test:
    name: "Portfolio Pipeline ✅"
    runs-on: ubuntu-latest

    steps:
      - name: Clonando o repositório dentro da VM
        uses: actions/checkout@v4.2.2

      - name: Configurando Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: "npm"

      - name: Instalando as dependências
        run: npm ci

      - name: Rodando a checagem de tipagem (tsc)
        run: npx tsc --noEmit

      - name: Rodando o ESLint
        run: npm run lint

      - name: Rodando testes unitários
        run: npm run test -- --watch=false --browsers=ChromeHeadless